name: 'Deploy project to AWS Elastic Beanstalk'
description: 'Deploy a project to AWS Elastic Beanstalk.'
author: 'Amrane Ait Zeouay'
runs:
  using: 'node16'
  main: 'deploy-beanstalk.js'
inputs:
  aws_access_key:
    description: 'AWS Access Key.'
    required: true
  aws_secret_key:
    description: 'AWS Secret Key.'
    required: true
  region:
    description: "AWS Environment's Region."
    required: true
  application_name:
    description: "AWS Elastic Beanstalk application's name."
    required: true
  environment_name:
    description: "AWS Elastic Beanstalk environment's name."
    required: true
  s3_bucket_name:
    description: "AWS S3 Bucket's name."
    required: true
  s3_file_path:
    description: 'AWS Elastic Beanstalk file path.'
    required: true
  ebs_version_label:
    description: 'AWS EBS version label.'
    required: true
  ebs_description:
    description: 'AWS EBS Description.'
    required: false
  ebs_wait_for_env_to_be_green:
    description: 'If we should wait for AWS Elastic Beanstalk environment to be green.'
    required: false
  updated_version_url:
    description: 'AWS EBS url to check the version deployed.'
    required: false
  expected_version:
    description: "AWS EBS application's expected version that should be delpoyed."
    required: false
  enable_debug:
    description: 'To enable debug and display logs.'
    required: false
  use_same_version:
    description: 'If you want to use the same version in AWS EBS, in case the version already exist.'
    required: false

branding:
  icon: 'arrow-up'
  color: 'green'
