name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on AWS Elastic Beanstalk Environment
        id: ebs-env
        uses: Dealermade/aws-beanstalk-deploy@master
        with:
          region: ${{ secrets.AWS_REGION }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          s3_bucket_key: ${{ secrets.AWS_BUCKET_KEY }}
          s3_file_path: ${{ secrets.AWS_FILE_PATH }}
          ebs_version_label: ${{ github.sha }}
          ebs_description: ${{ github.sha }}
          ebs_wait_for_env_to_be_green: true
